# -*- coding: utf-8 -*-
"""tic_tac_toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eD5gb-PuiH8N9ttJWnqgSw_xVzmkrHVr
"""

board = [['-', '-', '-'], ['-', '-', '-'], ['-', '-', '-']] #this list contains three lists, each of three elements, each element being a single character

def print_board():
  for r in board:
    print(r)

def check_mark():
  pass

def place_mark():
  pass

def check_win():
  pass

def main():
  pass

print_board()